.TH PRAISELANG "1" "January 2023" "GNU/UNIX Cryptography Tool" "Cryptographic System"
.SH NAME
praiselang \- encrypt and decrypt data by using praiselang algorithm
.SH SYNOPSIS
.B praiselang
[\fI\,OPTION\/\fR]... [\fI\,DATA\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
encrypt and decrypt data by using an algorithm named praiselang. It uses a substitution algorithm with base64 together.
.TP
\fB\-e [DATA]\fR, \fB\-\-encrypt [DATA]\fR
encrypt the given data
.TP
\fB\-d [DATA]\fR, \fB\-\-decrypt [DATA]\fR
decrypt the given encrypted data
.TP
\fB\-h\fR, \fB\-\-help\fR
show a simple help menu
.TP
\fB\-v\fR, \fB\-\-version\fR
show praiselang version
.TP
\fB\-g\fR, \fB\-\-github\fR
show github url of the repository
.SH AUTHOR
Written by Mehmet Mert Gunduz.
.SH "REPORTING BUGS"
Open an issue: <https://github.com/MertGunduz/praiselang/issues/new/>
.SH COPYRIGHT
Copyright \(co 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation <https://mertgunduz.github.io/praiselang/index.html>
.br